import type { ClubPreset } from "./types";
import type { BrandingColors } from "@/lib/types";

/**
 * The blank club: what a slug with no preset of its own renders before anyone
 * has opened Admin -> Branding.
 *
 * Deliberately anonymous. Not a nicer-looking club, not a demo club, and above
 * all not somebody else's club: a dark neutral room with bone-coloured lines
 * and placeholder art that reads as "nobody has set this up yet". That is the
 * honest state of an unbranded tenant, and it is the only state that cannot
 * put one club's colours on another club's page.
 *
 * The palette is intentionally desaturated. A new club should look UNFINISHED
 * rather than finished-in-the-wrong-colours, because the second is the one
 * that ships to members by accident.
 */

const SHARED_COLORS = {
  background: "#0A0A0C",
  foreground: "#E8E8EA",
  card: "#141417",
  cardForeground: "#E8E8EA",
  // Slate, not red. Nothing here should read as a club colour.
  primary: "#6B7280",
  primaryForeground: "#F5F5F6",
  secondary: "#1E1E22",
  secondaryForeground: "#E8E8EA",
  muted: "#1E1E22",
  mutedForeground: "#9A9AA2",
  accent: "#2A2A30",
  accentForeground: "#E8E8EA",
  destructive: "#B03A34",
  ring: "#6B7280",
  glow: "#6B7280",
  elevated: "#1B1B1F",
} as const;

const neutralColors: BrandingColors = {
  ...SHARED_COLORS,
  border: "rgba(232,232,234,0.12)",
  input: "rgba(232,232,234,0.20)",
  sidebar: "#08080A",
  sidebarBorder: "rgba(232,232,234,0.14)",
};

/** Placeholder artwork, generated by scripts/make-placeholder-art.ts. */
const A = (name: string) => `/brand/_platform/${name}.webp`;

export const PLATFORM_PRESET: ClubPreset = {
  slug: "_platform",

  identity: {
    displayName: "New Club",
    publicName: "New Club",
    legalName: "New Club",
    // Empty on purpose: resolveBranding falls through to initialsOf(name), so
    // an unbranded club shows its OWN initials rather than a placeholder.
    shortName: "",
    location: "",
    addressLine: "",
    portalTagline: "",
    publicTagline: "",
    mission: "",
    // A structural heading, not one club's writing (like "About Us" above);
    // the blurb is deliberately plainer than any club's own line.
    chainTitle: "Brotherhood",
    chainBlurb: "The chain of command, from the president down.",
    // No anthem until a club picks one. The layouts skip <MusicPlayer> on an
    // empty id; the player itself has no such guard, and mounting it with one
    // loads the embed and parks "This video is unavailable" on the page.
    anthemVideoId: "",
  },

  colors: { portal: neutralColors, public: neutralColors },

  fonts: {
    display: "var(--font-blackletter)",
    body: "var(--font-inter)",
    mono: "var(--font-jetbrains)",
  },

  assets: {
    rosterBackdrop: A("backdrop-portrait"),
    portalRosterBackdrop: A("backdrop-portrait"),
    characterStage: A("stage-landscape"),
    clubPatch: A("patch"),
    logo: A("wordmark"),
    heroImage: A("hero"),
    watermark: A("watermark"),
    // The one shipped file that was already brand-neutral: a shadow figure
    // with no club marks on it. Shared on purpose — it depicts "a person".
    defaultAvatar: "/brand/members/silhouette.webp",
    emblemOne: A("emblem"),
    emblemTwo: A("emblem"),
    emblemThree: A("emblem"),
    emblemFour: A("emblem"),
  },

  // No plate: <ChainOfCommand> falls back to the stacked panel, which needs no
  // art and lays out for any headcount. Far better than borrowing a plate with
  // another club's name engraved across it.
  plateArt: null,

  heroVideo: null,

  copy: {
    story: [],
    storyTitles: [],
    creed: [],
    values: [],
    pillars: [
      { title: "About Us", body: "Tell visitors who {club} is.", href: "about", cta: "Read More" },
      { title: "Brotherhood", body: "Introduce the people who ride under the colors.", href: "brotherhood", cta: "Meet the Club" },
      { title: "Our Code", body: "Set out what the club stands for.", href: "about", cta: "Read More" },
      { title: "Join the Club", body: "Tell prospects how to start.", href: "join", cta: "Apply Now" },
    ],
    closingHeading: "",
    closingBody: "",
  },

  contact: {
    venue: "",
    addressLines: [],
    hours: [],
  },
};
